### ISSUE TITLE
respect `typescript.suggest.completeFunctionCalls` settings

### ISSUE THREAD

**Issue by tjx666** [zardoy/typescript-vscode-plugins#114]
I don't like use this feature

**Comment by zardoy** [comment]
I didn't get it from first look, but do you mean method snippets that are enabled by default? (I believe this is documented feature).

Method snippets are enabled by default for a long time, didn't remember why I enabled them by default, but you can disable them by using `"tsEssentialPlugins.enableMethodSnippets": false` setting.

Of course, I could use existing `typescript.suggest.completeFunctionCalls` setting to determine wether to enable these method snippets or not, but this is vscode's implementation which overrides my implementation, and someone might prefer to use it instead of my implementation, because vscode's implementation uses insert text on completions and my implementation inserts additional text after completion accept, so you cant see text being inserted when ghost text is enabled (`"editor.suggest.preview": true`).

> I don't like use this feature

Also if you know how it can be improved, let me know.

**Comment by tjx666** [comment]
Why I don't like to enable `typescript.suggest.completeFunctionCalls` is because often trigger autocomplete in case I dont't want:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/41773861/224566994-42a75bcd-cd65-45e5-97f6-f188b3d524b0.png">

I just disable `tsEssentialPlugins.enableMethodSnippets` setting.

**Comment by zardoy** [comment]
> because often trigger autocomplete in case I dont't want

I have `disableMethodSnippets.*` setting (only a way to disable method snippets in jsx attributes for now), but I can extend it to support disabling in function arguments and assignments (`a: `, `a = `) in the same way

**Comment by tjx666** [comment]
This is my before solution https://github.com/microsoft/vscode/issues/133815
But it would be more convinient ts can skip complete function call intelligent

**Comment by zardoy** [comment]
> This is my previous solution proposed in microsoft/vscode#133815, but it would be more convenient if TypeScript could skip complete function calls intelligently.

We can add a setting so you need to accept suggestion twice in order to insert method snippet.

> Seems disableMethodSnippets.* a good solution.

Gonna be honest, don't really have much free time for this, but would be happy to review it
