### ISSUE TITLE
0.0.54: TypeScript completion got frozen

### ISSUE THREAD

**Issue by fifv** [zardoy/typescript-vscode-plugins#123]
Thank you for the amazing extension!

After updating to 0.0.54, TypeScript completion got frozen and occupies high cpu.

Repo: (I test this in a empty vscode(1.77.0 & 1.77.1) profile)
1. create a `main.ts` file
2. write this
```ts
const a = {
   // <- 3. then ctrl+space here, and it got stuck
}
```

If I install the `0.0.53` version, everything goes well
I have tried early versions of `JavaScript and TypeScript Nightly` but nothing changed

**Comment by zardoy** [comment]
Thank you so much for reporting this! I was extremely surprised that [infinite-loop aware code](https://github.com/zardoy/typescript-vscode-plugins/blob/f862cb600b3809b742d88b66692dd24b610d577f/typescript/src/completions/objectLiteralCompletions.ts#L26) was incorrectly fixed by eslint rule which started causing infinite loop, my bad I should've noticed this change. On the other hand I didn't notice it personally after plugin update because I'm using `"tsEssentialPlugins.objectLiteralCompletions.keepOriginal": "remove"` along with this keybinding:
```json
{
    "key": "shift+enter",
    "when": "suggestWidgetVisible && editorLangId != vue",
    "command": "tsEssentialPlugins.insertNameOfCompletion"
}
```

so I don't have 2x more variants in completion widget. I also recommend it, super useful.

**Comment by fifv** [comment]
It works, thank you for your effort!
