### ISSUE TITLE
Restore Properties Sorting is not working

### ISSUE THREAD

**Issue by svipas** [zardoy/typescript-vscode-plugins#141]
<img width="601" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/10441177/e89e098f-ef9e-4fc9-a67a-f1b410aaa940">

As you can see from the image with setting `"tsEssentialPlugins.fixSuggestionsSorting": true,` it still returns them in alphabetical order.

It is really cool setting, I hope there's a way to make it work. What I don't understand is why the hell TS has to do it alphabetical, I mean after I discovered this setting it is so obvious that this should be the default...

VS Code: 1.80.0
TS: 5.1.3
Extension: 0.0.63

**Comment by zardoy** [comment]
> It is really cool setting, I hope there's a way to make it work.

Oh, I actually broke it a few releases ago, and didn't notice that, for me it was workin perfectly. The reason why it broke is because of this

![image](https://github.com/zardoy/typescript-vscode-plugins/assets/46503702/f0d974ee-e03d-4070-ab5d-6a69ad303bc6)

I was trying to fix this behavior, here it should follow basic sorting rules (requires go before optional for convenience)

> What I don't understand is why the hell TS has to do it alphabetical

You're literally the second who thinks it can be not useful in some cases.


Also I've seen it conflicts with `suggestions.localityBonus`, I'm not sure what will be right here, but I'm disabling localityBonus for non global completions, WDYT?

**Comment by zardoy** [comment]
I just made a new release, let me know if everything is fine

btw defineStore and createSlice from redux toolkit are two cases why I created this feature

**Comment by zardoy** [comment]
to fix:

```ts
const a = {
  b: 5,
  a: 3
}

for (const {/*1*/} of [a]) {}

declare const test: <T>(obj: T) => T
const {/*2*/} = test(a)
```
