### ISSUE TITLE
Deprecate `experiments.changeKindToFunction`, replace its functionality with `methodSnippetsInsertText`

### ISSUE THREAD

**Issue by zardoy** [zardoy/typescript-vscode-plugins#146]
e.g. current behavior that can be enabled only with `experiments.changeKindToFunction`, should now also be enabled with `methodSnippetsInsertText` setting. The first setting should be deprecated like `you need to use methodSnippetsInsertText setting instead`

**Comment by svipas** [comment]
Totally agree, because with `"tsEssentialPlugins.methodSnippetsInsertText": "all"` I can see function if declared variable is function. Also, they both didn't worked quite well to be honest.

<img width="251" alt="image" src="https://github.com/zardoy/typescript-vscode-plugins/assets/10441177/aa43d348-0f5e-4705-9079-ad98c5389f8d">
