### ISSUE TITLE
Remove (or change sorting) for useless suggestions for standard keywords

### ISSUE THREAD

**Issue by AgentRBY** [zardoy/typescript-vscode-plugins#58]
Hi! 👋

I suggest removing or changing the sorting for standard keywords like while, function, import, etc

Example: I enter `whi` for snippet `while () {}`, editor offers me first `while` and only then snippet. This is terribly annoying and slows down development sometimes
![image](https://user-images.githubusercontent.com/68181944/199700483-ebf658c2-6a18-47e6-9125-83b32f2de91e.png)
![image](https://user-images.githubusercontent.com/68181944/199701288-90d52c12-6ea6-4432-b573-3790e1c57732.png)
![image](https://user-images.githubusercontent.com/68181944/199701625-238e56eb-557e-41d9-843d-35d1ee37df65.png)

**Comment by zardoy** [comment]
> This is terribly annoying and slows down development sometimes

Damn you're right! 100% agree with you and there are many ways to solve that

## Ways to fix it

### 1. Remove needed keyword suggestions completely

```json
"tsEssentialPlugins.replaceSuggestions": [
    {
        "suggestion": "new",
        "filter": {
            "kind": "keyword"
        },
        "delete": true
    },
    {
        "suggestion": "do",
        "filter": {
            "kind": "keyword"
        },
        "delete": true
    },
]
```

and so on...

### 2. Change keywords to use snippet text

For example:

```json
"tsEssentialPlugins.replaceSuggestions": [
    {
        "suggestion": "import",
        "patch": {
            "insertText": "import $2 from '$1'"
        }
    },
]
```

You actually stick to this one if you don't use Vue or Svelte (as this plugin is not supported in these languages for now).

### 3. Make keywords actually show below snippets

This is finally what you've been requesting Xd.

Let's dig into `import` snippet case. As I can see from your screenshot, you're using builtin snippet from [JavaScript extension](https://github.com/microsoft/vscode/blob/26155fc874f92baa48c3800f1d3b58c3a59ee55c/extensions/javascript/snippets/javascript.code-snippets#L152). There is [hardcoded logic in vscode](https://github.com/microsoft/vscode/blob/f3f9f7a10d877fd2177daec3e1f6054706c7e5bc/src/vs/workbench/contrib/snippets/browser/snippetCompletionProvider.ts#L57) that snippets from extension have `z-` prefix in sortText. However, even if the snippet is defined on the workspace level (will have `a-` prefix) they will still be displayed below the keywords suggestions (as TS suggestions have numbers in `sortText`).

You can either just set `"editor.snippetSuggestions": "top"` setting to make any snippet show on top.

Or of course, you can just lower `sortText` of TS keywords suggestions like so:

```json
"tsEssentialPlugins.replaceSuggestions": [
    {
        "suggestion": "import",
        "patch": {
            "sortText": "zz"
        }
    },
]
```

But it also doesn't seem to be ideal:

<img width="400" alt="Screenshot 2022-11-04 at 01 10 31" src="https://user-images.githubusercontent.com/46503702/199844074-3a8b50ed-9125-4c81-b10e-a0833a3f6608.png">

In case `import` and `function` I personally use snippets from Better Snippets. Since I have to write imports really often, I'm using [this typing snippet](https://github.com/zardoy/vscode-better-snippets-packs/blob/59429a30d07dcbad4b7ec073fda6220873322863/packs/ts-typing/index.ts#L34-L40) for that. But you can use custom snippet as well with `"sortText": "!"`.

---

What about first two cases I understand that it may not be clear from the current docs, but have no idea how to improve it.

**Comment by AgentRBY** [comment]
Cool! Thank you!
