### ISSUE TITLE
What is vueSpecificImprovements?

### ISSUE THREAD

**Issue by tjx666** [zardoy/typescript-vscode-plugins#88]
I see there is a setting `tsEssentialPlugins.vueSpecificImprovements` and enabled by default, but don't know what it is. Maybe we need add some description about this setting.

**Comment by zardoy** [comment]
Being declared in 
https://github.com/zardoy/typescript-vscode-plugins/blob/bc0d31a81f3ff9b56e37fef30fa68e730be01202/src/configurationType.ts#L69
and used only in
https://github.com/zardoy/typescript-vscode-plugins/blob/873c2d1c83fe143f09c2f32b74ac1e4f84d989de/typescript/src/completionsAtPosition.ts#L219-L226

It is currently used to remove special types in legacy `defineComponent` from completions (but this not something that user want to disable)

But I don't really remember why I added this setting, probably I also wanted to include something else...
Anyway since name isnt straightforward I'll remove this setting.
