### ISSUE TITLE
repeat suggestions

### ISSUE THREAD

**Issue by tjx666** [zardoy/typescript-vscode-plugins#90]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/215274574-f94e4ace-4772-4c7c-9c21-39abdbfceb4b.png">

**Comment by zardoy** [comment]
Did you mean there is an issue with repeated suggestions?

Hm.. I see it's not documented in readme but in this plug-in it's called object literal suggestions ([implementation](https://github.com/zardoy/typescript-vscode-plugins/blob/develop/typescript/src/completions/objectLiteralCompletions.ts), can be disabled with `objectLiteralCompletions.moreVariants` setting), there are enabled by default because `includeCompletionsWithObjectLiteralMethodSnippets` is also enabled by default (these duplicated method suggestions are builtin)

**Comment by tjx666** [comment]
In face, I think here just suggest `title?: ''` is enough, the `title?` is useless for me...

**Comment by zardoy** [comment]
> In fact, I think here just suggest title?: '' is enough, the title? is useless for me...

We don't know, maybe there is `title` variable in this scope and you want to use shorthand.

But if you want, you can set `"tsEssentialPlugins.objectLiteralCompletions.keepOriginal": "remove"` to remove these useless suggestions, which is generally recommended. Next, I have plans to show these "useless" suggestions for shorthand option (see last task in https://github.com/zardoy/typescript-vscode-plugins/issues/82)
