### ISSUE TITLE
[Feature Request] go to import

### ISSUE THREAD

**Issue by tjx666** [zardoy/typescript-vscode-plugins#91]
I often use go to definition to check a variable where it is define.
When a variable is imported, I want go to the statement not go that module.

```typescript
// a.ts
export function add() {}
```

```typescript
// b.ts
import {add} from 'a'

// ...many code

add();
```

I hope there is a contextMenu Item named `Go to Import` I can jump to import statement of add.
When the variable is not imported and defined local, will fallback to `Go to Definition`

**Comment by tjx666** [comment]
Maybe the command name `Go to Import` is not good, but want there is a command can make me to go to import statement but not go to another file.

**Comment by zardoy** [comment]
This is was one of the first ideas of this extension: https://github.com/zardoy/typescript-vscode-plugins/issues/26 as replacing variable from other module was a common case for me. But I was using `Highlight Utils: Go to Highlighted Locations` command all the time (it recently was moved to [Highlight Utils](https://marketplace.visualstudio.com/items?itemName=zardoy.highlight-utils)), because it is language-agnostic. With this command you can see import as first result. Let me know what you think of this approach!

> I hope there is a contextMenu item

I don't have an extension that adds any items to editor menu, as it is not possible remove them. Also unfortunately VSCode doesn't provide an easy to add custom commands, its not really configurable. However, you can add custom commands to context menu via another extension.

**Comment by tjx666** [comment]
> it is not possible remove them

You can use custom context and when clause, combine with a enable setting. Check here for example: https://github.com/tjx666/vscode-clipboard-master/blob/main/package.json#L151

- https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context

**Comment by zardoy** [comment]
> You can use custom context and when clause, combine with a enable setting.

Agree, I just remembered that its possible to use *Configuration settings contexts* like `"when": "config.someExt.enableSomeItemContextMenu"`

**Comment by zardoy** [comment]
Opened https://github.com/zardoy/typescript-vscode-plugins/issues/111, probably you wanted this instead, so feel free to pr if you still need it
